title: Welcome to my page!
author: Gautham Thodar
email: tgautham.kamath@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a cloud enthusiast and a data nerd

# social links
github_username:  tgauthamkamath

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

